import type { z } from "zod";
import type { LlmMessage, LlmProvider } from "./types.js";
import {
  PlanOutputSchema,
  PatchOutputSchema,
  ReviewOutputSchema,
} from "../schemas/index.js";
import { createUnifiedDiff } from "../diff/apply.js";

const OUTPUT_TAG = /\[OUTPUT_TYPE:(plan|patch|review)\]/;

/** Deterministic provider for tests and offline demo without API keys. */
export class MockLlmProvider implements LlmProvider {
  readonly name = "mock";

  async structured<T>(
    schema: z.ZodType<T>,
    messages: LlmMessage[],
    _model: string,
  ): Promise<T> {
    const system = messages.find((m) => m.role === "system")?.content ?? "";
    const user = messages.filter((m) => m.role === "user").pop()?.content ?? "";
    const tag = system.match(OUTPUT_TAG)?.[1] ?? "patch";

    if (tag === "plan") {
      return PlanOutputSchema.parse({
        summary: `Plan for: ${user.slice(0, 120)}`,
        tasks: [
          {
            id: "task-1",
            agent: "backend",
            description: `Implement: ${user.slice(0, 200)}`,
            status: "pending",
          },
          {
            id: "task-2",
            agent: "qa",
            description: "Validate implementation and edge cases",
            status: "pending",
          },
        ],
        questions: [],
      }) as T;
    }

    if (tag === "review") {
      return ReviewOutputSchema.parse({
        summary: /validat|test/i.test(user)
          ? "QA validation (mock)"
          : "Architecture review (mock)",
        findings: [
          {
            severity: "info",
            message: /validat/i.test(user)
              ? "Add tests for error paths and token expiry."
              : "Consider separating auth module from routes.",
          },
        ],
        approved: true,
      }) as T;
    }

    const targetFile = /jwt|auth/i.test(user)
      ? "src/auth/jwt.service.ts"
      : "src/generated/feature.ts";
    const newContent = `// Generated by AI Shell (mock)\n// ${user.slice(0, 120)}\n\nexport function mockFeature() {\n  return { ok: true };\n}\n`;

    return PatchOutputSchema.parse({
      summary: `Mock implementation for ${targetFile}`,
      patches: [
        {
          filePath: targetFile,
          unifiedDiff: createUnifiedDiff(targetFile, "", newContent),
          description: user.slice(0, 100),
        },
      ],
    }) as T;
  }

  async complete(messages: LlmMessage[], _model: string): Promise<string> {
    const user = messages.filter((m) => m.role === "user").pop()?.content ?? "";
    return `[mock] ${user.slice(0, 200)}`;
  }
}
